### ISSUE TITLE
css symbols are wrong

### ISSUE THREAD

**Issue by TristanTrim** [Rhombik/rhombik-object-repository#52]
css elements that should be search and checkmark symbols are not displayed that way for me. See picture.
![bug](https://cloud.githubusercontent.com/assets/3712921/5681287/96135856-97ed-11e4-82ab-4b56096a35d3.jpg)

**Comment by traverseda** [comment]
Enable javascript you newb.

I'm not clear on why font icons need js, or why yours show up as hebrew without JS. Either way it's an upstream issue.
